# Needs to remain [push] only, no pull-request at the moment
# as "Integration tests" runs self-hosted and github settings are limited.
# https://github.community/t/self-hosted-runner-security-with-public-repositories/17860
on: [push]

defaults:
  run:
    shell: bash

name: Integration tests (skylake2x)
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/doc/**", "**/verification/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  test-skylake2x:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: [self-hosted, skylake2x]
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init
          rustup show
      - name: Integration tests (qemu/kvm)
        run: |
          bash setup.sh
          cd kernel
          RUST_TEST_THREADS=1 cargo test --features smoke
  bench-skylake2x:
    needs: [pre_job, test-skylake2x]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: [self-hosted, skylake2x]
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init
          rustup show
      - name: Run Benchmarks
        run: |
          bash setup.sh
          bash scripts/ci.bash
    env:
      CI_MACHINE_TYPE: "skylake2x"
